version: '3'
services:

  spring-of-emails:
    build: 
      spring-of-emails
    depends_on:
      - postgres
      - redis
    ports:
      - 8080
    links:
      - redis
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - spring-of-emails
    ports:
      - 80:80


  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    hostname: postgres
    ports:
      - 5432:5432

  redis:
    image: redis:6.0.10-alpine
    hostname: redis
    ports:
      - 6379:6379
   

networks:
  mynetwork:
    driver: bridge
